---
title: "A5_review_pranav_tirthraj_shreysa"
author: "pranav-shreysa-tirthraj"
date: "October 24, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://github.ccs.neu.edu/pdpmr-f17/a5-aditya-apoorv-dhvani.git

## Following steps were taken to run the program
1) Changed the hadoop path, placed the input directory and query file in the folder and entered the path in the makefile.
2) issued make build and make run and the program runs fine.


## Code setup and Execution
1) Code is not split into parts making it hard to read.
2)Redundant code is present with multiple lines doing the same calls and doing the same things.Example of the if  condition below-

```
        if (mapper.equals(FIRSTHOP)) {
            StringBuilder sb = new StringBuilder();
            String firstHop = record[1];
            String[] firstHopSplit = firstHop.split(CSV_SEP);
            sb.append(firstHopSplit[1]);
            sb.append(CSV_SEP);
            sb.append(firstHopSplit[5]);
            sb.append(CSV_SEP);
            sb.append(firstHopSplit[6]);
            sb.append(CSV_SEP);
            sb.append(firstHopSplit[7]);
            outputKey.set(sb.toString());
            String valueString = value.toString();
            outputValue.set(FIRSTHOP + SPACE + valueString);
            context.write(outputKey, outputValue);
        }
        else {
            String secondHop = record[2];
            String[] secondHopSplit = secondHop.split(CSV_SEP);
            StringBuilder sb2 = new StringBuilder();
            sb2.append(secondHopSplit[1]);
            sb2.append(CSV_SEP);
            sb2.append(secondHopSplit[4]);
            sb2.append(CSV_SEP);
            sb2.append(secondHopSplit[5]);
            sb2.append(CSV_SEP);
            sb2.append(secondHopSplit[6]);
            outputKey.set(sb2.toString());
            String valueString = value.toString();
            outputValue.set(SECONDHOP+ SPACE + valueString);
            context.write(outputKey, outputValue);
        }
```

3) It is difficult to understand the code and how it functions because the code is not split and does multiple things at a time.
4) The readme file is not clear enough to give details on how to execute the program.
5) Records/Column names are fetched based on the column numbers,which is a bad technique in general.
6) HopReducer/Hopmapper code is extremely hard to understand because of not splitting code into methods and no comments for what some defined methods do.
7) I could not get the code to run,even after following the steps outlined in the readme file.

## Report
1) Report explains things clearly.
2) The prediction accuracy mentioned helps in giving a overview of the model and its use.
3) The runtime information seems to show that the program execution times decreased as the nodes were increased,indicating a good approach.
4) The graphical representation makes it easy to understand which cases were predicted correctly vs which were predicted incorrectly but does not give any information about which flight,how etc. The graphical representation could have been for other parameters instead of the ones shown.
5) Overall,the report is clean and does not contain many errors.



